# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(761, 308)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 741, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setStyleSheet("font-weight:bold;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label.setStyleSheet("font-weight:bold;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.rollSpin = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rollSpin.sizePolicy().hasHeightForWidth())
        self.rollSpin.setSizePolicy(sizePolicy)
        self.rollSpin.setObjectName("rollSpin")
        self.gridLayout.addWidget(self.rollSpin, 0, 2, 1, 1)
        self.nutPrice = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nutPrice.setText("")
        self.nutPrice.setObjectName("nutPrice")
        self.gridLayout.addWidget(self.nutPrice, 1, 1, 1, 1)
        self.rollTotalPrice = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.rollTotalPrice.setReadOnly(True)
        self.rollTotalPrice.setObjectName("rollTotalPrice")
        self.gridLayout.addWidget(self.rollTotalPrice, 0, 3, 1, 1)
        self.rollPrice = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.rollPrice.setText("")
        self.rollPrice.setObjectName("rollPrice")
        self.gridLayout.addWidget(self.rollPrice, 0, 1, 1, 1)
        self.nuttSpin = QtWidgets.QDoubleSpinBox(parent=self.gridLayoutWidget)
        self.nuttSpin.setObjectName("nuttSpin")
        self.gridLayout.addWidget(self.nuttSpin, 1, 2, 1, 1)
        self.nutTotalPrice = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nutTotalPrice.setReadOnly(True)
        self.nutTotalPrice.setObjectName("nutTotalPrice")
        self.gridLayout.addWidget(self.nutTotalPrice, 1, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Sklep"))
        self.label_2.setText(_translate("Dialog", "Orzechy"))
        self.label.setText(_translate("Dialog", "Bułka"))
        self.nutPrice.setPlaceholderText(_translate("Dialog", "Cena za kg"))
        self.rollPrice.setPlaceholderText(_translate("Dialog", "Cena za sztukę"))
